version: '3'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - dist_volume:/app/dist

  web:
    build:
      context: .
      dockerfile: Dockerfile.serve
    ports:
      - "8080:80"
    volumes:
      - dist_volume:/usr/share/nginx/html
    depends_on:
      - builder
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.html"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  dist_volume: