version: '3'
name: game1

services:
  builder:
    build:
      context: ../..
      dockerfile: docker/builder/Dockerfile
    volumes:
      - nginx_html:/usr/share/nginx/html

  web:
    build:
      context: ../..
      dockerfile: docker/web/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - nginx_html:/usr/share/nginx/html
    depends_on:
      - builder
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.html"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  nginx_html: