version: '3'
name: game1  # プロジェクト名を明示的に指定

services:
  builder:
    build:
      context: ../..
      dockerfile: docker/builder/Dockerfile
    volumes:
      - ../../src:/app/src
      - ../../public:/app/public
      - dist_volume:/app/dist

  web:
    build:
      context: ../..
      dockerfile: docker/web/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - dist_volume:/usr/share/nginx/html
    depends_on:
      - builder
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.html"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  dist_volume: